# Generated by Django 4.1.4 on 2023-01-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=512, verbose_name='Описание')),
                ('post', models.TextField(verbose_name='Запись блога')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('autor', models.CharField(default='admin', max_length=64, verbose_name='Автор')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='Слаг')),
            ],
        ),
    ]
